--001-event.sql

-----------------------------------------------------------------------
-- slack.event
create table if not exists slack.event
( id int8 not null generated by default as identity
, event_ts timestamptz not null default now()
, type text not null
, subtype text
, event jsonb
, error jsonb
)
with
( tsdb.hypertable
, tsdb.partition_column='event_ts'
);

-----------------------------------------------------------------------
-- slack.bot_event
create table slack.bot_event
( id int8 not null primary key generated by default as identity
, event_ts timestamptz not null default now()
, attempts int4 not null default 0
, vt timestamptz not null default now() -- visibility threshold
, event jsonb
);

-----------------------------------------------------------------------
-- slack.bot_event_hist
create table if not exists slack.bot_event_hist
( id int8 not null
, event_ts timestamptz not null default now()
, attempts int4 not null default 0
, vt timestamptz not null default now() -- visibility threshold
, event jsonb
) with (
  tsdb.hypertable,
  tsdb.partition_column='event_ts'
);