--001-event.sql

-----------------------------------------------------------------------
-- slack.event
-- this table is used for debugging and post-analysis
create table if not exists slack.event
( id int8 not null generated by default as identity -- for uniqueness but doesn't need to be enforced
, event_ts timestamptz not null default now()
, type text not null
, subtype text
, event jsonb
, error jsonb
)
with
( tsdb.hypertable
, tsdb.partition_column='event_ts'
, tsdb.chunk_interval='7 days'
, tsdb.enable_columnstore=true
, tsdb.orderby = 'event_ts desc'
, tsdb.sparse_index='minmax(id)'
);
create index on slack.event (event_ts desc) where error is not null;
create index on slack.event (type, subtype);
create index on slack.event (id);

perform public.add_retention_policy('slack.event'::regclass, interval '90 days');

