--001-event.sql

-----------------------------------------------------------------------
-- slack.event
create table if not exists slack.event
( id int8 not null generated by default as identity
, event_ts timestamptz not null default now()
, type text not null
, subtype text
, event jsonb
, error jsonb
)
with
( tsdb.hypertable
, tsdb.partition_column='event_ts'
);
