name: Build Docker MCP - Feature Branch Push
on:
  push:
    branches-ignore:
      - main
    paths:
      - "mcp/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: build.yaml
          ref: "mpeveler/feat-docker-context"
          inputs: '{"docker_context": "./mcp", "image_name": "tiger-slack-mcp-server", "repository": "tiger-slack", "sha": "${{ github.sha }}"}'
