name: Build Docker Ingest - Feature Branch Push
on:
  push:
    branches-ignore:
      - main
    paths:
      - "ingest/**"
      - .github/workflows/*ingest*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: build.yaml
          ref: "main"
          inputs: '{"docker_context": "./ingest", "image_name": "tiger-slack-ingest", "repository": "tiger-slack", "sha": "${{ github.sha }}"}'
