name: Build and Deploy Ingest - Merge main
on:
  push:
    branches:
      - main
    paths:
      - "ingest/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: build.yaml
          ref: "main"
          inputs: '{"dockerfile_path": "./ingest/Dockerfile", "image_name": "tiger-slack-ingest", "repository": "tiger-slack", "sha": "${{ github.sha }}"}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: deploy.yaml
          ref: "main"
          inputs: '{"repository": "tiger-slack-ingest", "sha": "${{ github.sha }}"}'
