name: Code Quality
on: [pull_request]

jobs:
  ingest-quality:
    name: Ingest Service (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ingest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.API_TOKEN_GITHUB }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.6.12"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run linter
      run: uv run ruff check .
    
    - name: Check formatting
      run: uv run ruff format --diff --check .
    
    - name: Run type checking
      run: uv run pyright

  mcp-quality:
    name: MCP Server (TypeScript)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcp
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Setup Node.js
      
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ./mcp/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build and type check
      run: npm run build